apiVersion: v1
kind: Service
metadata:
  name: service-expose
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
      protocol: TCP